CREATE TABLE cars (
  id INT AUTO_INCREMENT PRIMARY KEY,
  brand VARCHAR(255),
  model VARCHAR(255),
  category VARCHAR(255),
  transmission VARCHAR(255),
  fuelType VARCHAR(255),
  plateNumber VARCHAR(255),
  year VARCHAR(10),
  month VARCHAR(10),
  mileage INT,
  power VARCHAR(50),
  displacement VARCHAR(50),
  technicalData TEXT,
  ownerCount VARCHAR(10),
  driveType VARCHAR(50),
  modelDetail VARCHAR(255),
  price DECIMAL(12,2),
  discountPrice DECIMAL(12,2),
  warranty VARCHAR(255),
  vatRefundable VARCHAR(10),
  vatRate VARCHAR(10),
  accident VARCHAR(255),
  vinCode VARCHAR(255),
  description TEXT,
  equipment TEXT,
  additionalInfo TEXT,
  country VARCHAR(10),
  phone VARCHAR(50),
  businessType VARCHAR(50),
  socialNetwork VARCHAR(255),
  email VARCHAR(255),
  image_1 VARCHAR(255),
  image_2 VARCHAR(255),
  image_3 VARCHAR(255),
  image_4 VARCHAR(255),
  image_5 VARCHAR(255),
  image_6 VARCHAR(255),
  image_7 VARCHAR(255),
  image_8 VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL
); 